name: icv_tp3
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - PIL
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - cudnn=7.6.5
  - pip
  - pip:
    - tqdm